# DB wali values (host, port, user, password) ab AWS Secrets Manager se aati hain (app-secret)
apiVersion: v1
kind: ConfigMap
metadata:
  name: backend-config
data:
  APP_ENV: local
  APP_DEBUG: "true"
  APP_URL: http://localhost:8000
  APP_TIMEZONE: Asia/Karachi
  SESSION_DRIVER: array
  CACHE_STORE: array
  SEED_DEMO_DATA: "true"
