apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      initContainers:
        # RDS ready / reachable hone tak intezar
        - name: wait-for-db
          image: busybox:1.36
          command: ["sh", "-c", "until nc -z $DB_HOST $DB_PORT; do echo waiting for rds; sleep 2; done"]
          envFrom:
            - secretRef:
                name: app-secret
      containers:
        - name: backend
          image: shahiddevops1/docslot-backend
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8000
          envFrom:
            - configMapRef:
                name: backend-config
            - secretRef:
                name: app-secret   # DB_CONNECTION, DB_HOST, DB_PORT, DB_DATABASE, DB_USERNAME, DB_PASSWORD
          readinessProbe:
            tcpSocket:
              port: 8000
            initialDelaySeconds: 15
            periodSeconds: 5
            failureThreshold: 30
